language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

jdk:
  - oraclejdk8

notifications:
  email: false

script:
  - ./gradlew clean
  - ./gradlew build connectedCheck --stacktrace
#  - ./gradlew assemble check
#  - ./gradlew checkstyle
#  - ./gradlew build