language: android
sudo: required
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-30.0.2
  - android-30
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
jdk:
- oraclejdk11
notifications:
  email: false
script:
- "./gradlew clean bundleProductionRelease"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-30"
- openssl aes-256-cbc -K $encrypted_4c721a8ffc8b_key -iv $encrypted_4c721a8ffc8b_iv
  -in apiKey.properties.enc -out apiKey.properties -d
