name: Room Example
run-name: ${{ github.actor }} is building Room Example 🚀
on:
  push:
    branches:
      - master
  pull_request:
    brances:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository initial
        run: ls ${{ github.workspace }}
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name : Verify Java Version
        run: java --version
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build apk release
        run: ./gradlew assembleProductionRelease
      - run: echo "🍏 This job's status is ${{ job.status }}."